### ISSUE TITLE
run in my data(10 class)

### ISSUE THREAD

**Issue by 18456432930** [UMBCvision/MSF#3]
I find a promeble in run python eval_knn.py and python eval_linear.py, the eval_linear.py is very low, but the python eval_knn.py result can get 0.95. this is why? I run in my data (10 class)

**Comment by chigur** [comment]
Hi @18456432930,

Since I've replied to this in the other [issue](https://github.com/UMBCvision/MSF/issues/2#issuecomment-847257134), I am closing the issue.

Thank You
Ajinkya Tejankar
