### ISSUE TITLE
Would you please share your pretrained weights?

### ISSUE THREAD

**Issue by CoinCheung** [UMBCvision/MSF#6]
Hi,

Thanks for bringing this great work to the community !!

Would you please share the checkpoint you have pretrained on imagenet?

**Comment by soroush-abbasi** [comment]
Hi, 

I uploaded the pretrained model on ImageNet( ResNet50, Topk=10, Memory bank size=1024k). Please let me know if you have any questions. Thanks!

**Comment by CoinCheung** [comment]
Thanks for sharing !! I am closing this, and I will leave messages here if I have other questions. Thanks again !!
