### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by dmlpt** [UMBCvision/MSF#7]
Hi,

Nice work! Could you please provide the following details:
a) How long did it take to finish the training (Resnet50 with 200 epochs)?
b) How many gpus did you use?
c) What gpus (memory) did you use?

Thanks in advance!

**Comment by soroush-abbasi** [comment]
Hi, 

Thanks for your interest in our work!

We train on 4 RTX6000 GPUs with 24GB of memory. But one can run our model with 4 RTX 2080Ti GPUs with 11GB of memory as well(with 128K memory bank). 200 Epochs of training with ResNet50 backbone will take approximately 140 hours to train. 

Please let us know if you need more information. Thanks!

**Comment by dmlpt** [comment]
I am assuming it is 140hrs on 4 RTX6000 gpus (not RTX 2080Ti). Thanks for the details.
