### ISSUE TITLE
MSE calculation

### ISSUE THREAD

**Issue by YunYunY** [UMBCvision/MSF#9]
Hi,

Thank you for sharing the code. I have a silly question regarding the MSE calculation. I found in your code, you used `dist_t = 2 - 2 * torch.einsum('bc,kc->bk', [current_target, targets])`. In my understanding, `torch.einsum('bc,kc->bk', [current_target, targets])` is calculating elementwise multiplication and sum them in c dimension. How does this result in MSE? 

Thank you.

**Comment by YunYunY** [comment]
Oh I see what you are doing. Closing the issue. Thank you.

**Comment by tsly123** [comment]
Hi @YunYunY 

Could you elaborate on how this line relates to MSE?
Thank you.

**Comment by tsly123** [comment]
Oh well, I've got it.
Thank you
